### ISSUE TITLE
Mechanical dimensions

### ISSUE THREAD

**Issue by dmoroni** [ivmech/ivport#1]
Could you provide some dimensions of the board so I can use it in a mechanical design?

**Comment by ivmech** [comment]
Dimensions are 56 x 38mm and 20mm height with stackable headers, 12mm height without stackable headers.

**Comment by dmoroni** [comment]
Thank you!

On Tue, Jan 20, 2015 at 11:08 PM, Ivmech Mechatronics Innovation Ltd. <
notifications@github.com> wrote:

> Dimensions are 56 x 38mm and 20mm height with stackable headers, 12mm
> height without stackable headers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ivmech/ivport/issues/1#issuecomment-70793709>.
>



-- 
Dan Moroni <http://www.linkedin.com/in/DMoroni>
Product Manager
408-636-4224
www.LiquidR.com <http://www.liquidr.com/>
@LiquidRInc <http://twitter.com/#!/liquidrinc>
Facebook <http://www.facebook.com/pages/Liquid-Robotics-Inc/192500987479045>
LinkedIn <http://www.linkedin.com/company/liquid-robotic>
