### ISSUE TITLE
How to power one camera at a time?

### ISSUE THREAD

**Issue by hmaarrfk** [ivmech/ivport#13]
The new 8MP seem to draw a lot more power. 

How do we configure the V3 board to only power one camera at a time?

**Comment by ivmech** [comment]
Hi, ivport is not compatible with camera v2 yet. We will release new version of ivport soon (first prototype is finished) for support 8mp camera.

**Comment by hmaarrfk** [comment]
Hmm, that is too bad. I had just bought an IVPort a few weeks ago and was hoping it was compatible.

Is it because the datarate is too high?
Or is it the power draw?

**Comment by ivmech** [comment]
Hi, 
Because they have used different sensor model,

**Comment by hmaarrfk** [comment]
Thanks, I guess I'll wait for the new model.
