### ISSUE TITLE
Version 2

### ISSUE THREAD

**Issue by dmoroni** [ivmech/ivport#2]
Are you working on a second revision? When can we expect for it to be ready? 

I was just about to buy one but they look out of stock. Also, you made a mention of a version 2 in your documentation. Any help is appreciated.

Thanks!

**Comment by ivmech** [comment]
Revision 2 is on production line, it will be available in 1 or 2 weeks, even you can place order.

Thanks,

**Comment by dmoroni** [comment]
So if I place an order now it will be fulfilled with revision 2?
Thank you for your quick response I will do that!
Sent from my iPhone




On Thu, Feb 26, 2015 at 10:49 PM -0800, "Ivmech Mechatronics Innovation Ltd." <notifications@github.com> wrote:












Revision 2 is on production line, it will be available in 1 or 2 weeks, even you can place order.



Thanks,

**Comment by ivmech** [comment]
Yes, revision 1 is out of stock and will not produced again,

Thanks,
